# Generated by Django 5.2.3 on 2025-06-15 23:53

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Personas',
            fields=[
                ('per_id', models.AutoField(primary_key=True, serialize=False)),
                ('per_segundo_nombre', models.CharField(default='Null', max_length=50, verbose_name='Segundo nombre:')),
                ('per_segundo_apellido', models.CharField(default='Null', max_length=50, verbose_name='Segundo apellido:')),
                ('per_edad', models.IntegerField(default=0, verbose_name='Edad:')),
                ('per_cedula', models.CharField(default='Null', max_length=15, verbose_name='Cédula:')),
                ('per_fecha_nacimiento', models.DateField(default='Null', verbose_name='Fecha de nacimiento:')),
                ('per_telefono', models.CharField(default='Null', max_length=15, null=True, verbose_name='Teléfono:')),
                ('per_fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Actualizado el:')),
                ('fk_id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Estudiantes',
            fields=[
                ('est_id', models.AutoField(primary_key=True, serialize=False)),
                ('est_fotografia', models.ImageField(blank=True, default='Sin Foto', null=True, upload_to='estudiantes/', verbose_name='Fotografía:')),
                ('est_contacto_emergencia', models.CharField(default='Null', max_length=50, null=True, verbose_name='Contacto de emergencia:')),
                ('est_telefono_emergencia', models.CharField(default='Null', max_length=15, null=True, verbose_name='Teléfono de emergencia:')),
                ('est_estado', models.BooleanField(default=True, verbose_name='Estado:')),
                ('est_fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Actualizado el:')),
                ('fk_id_persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.personas', verbose_name='Persona')),
            ],
        ),
        migrations.CreateModel(
            name='Docentes',
            fields=[
                ('doc_id', models.AutoField(primary_key=True, serialize=False)),
                ('doc_cargo', models.CharField(default='Null', max_length=100, verbose_name='Cargo:')),
                ('doc_fotografia', models.ImageField(default='Sin Foto', upload_to='docentes/', verbose_name='Fotografía:')),
                ('doc_estado', models.BooleanField(default=True, verbose_name='Estado:')),
                ('doc_fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Actualizado el:')),
                ('fk_id_persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.personas', verbose_name='Persona')),
            ],
        ),
        migrations.CreateModel(
            name='Administradores',
            fields=[
                ('adm_id', models.AutoField(primary_key=True, serialize=False)),
                ('adm_estado', models.BooleanField(default=True, verbose_name='Estado:')),
                ('adm_fecha_creacion', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación:')),
                ('adm_fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Actualizado el:')),
                ('fk_id_persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.personas', verbose_name='Persona')),
            ],
        ),
    ]
