# Generated by Django 5.1 on 2025-06-23 06:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Docentes',
            fields=[
                ('doc_id', models.AutoField(primary_key=True, serialize=False)),
                ('doc_cargo', models.CharField(default='Null', max_length=100, verbose_name='Cargo:')),
                ('doc_fotografia', models.ImageField(default='Sin Foto', upload_to='docentes/', verbose_name='Fotografía:')),
                ('doc_estado', models.BooleanField(default=True, verbose_name='Estado:')),
            ],
        ),
        migrations.CreateModel(
            name='Estudiantes',
            fields=[
                ('est_id', models.AutoField(primary_key=True, serialize=False)),
                ('est_contacto_emergencia', models.CharField(default='Null', max_length=50, null=True, verbose_name='Contacto de emergencia:')),
                ('est_telefono_emergencia', models.CharField(default='Null', max_length=15, null=True, verbose_name='Teléfono de emergencia:')),
                ('est_fotografia', models.ImageField(blank=True, default='Sin Foto', null=True, upload_to='estudiantes/', verbose_name='Fotografía:')),
                ('est_estado', models.BooleanField(default=True, verbose_name='Estado:')),
            ],
        ),
        migrations.CreateModel(
            name='Modulos',
            fields=[
                ('mod_id', models.AutoField(primary_key=True, serialize=False)),
                ('mod_nombre', models.CharField(max_length=50, unique=True, verbose_name='Nombre del modulo:')),
                ('mod_descripcion', models.CharField(max_length=100, verbose_name='Descripción del modulo:')),
                ('mod_estado', models.BooleanField(default=True, verbose_name='Estado:')),
                ('mod_fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Creado el:')),
                ('mod_fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Actualizado el:')),
            ],
        ),
        migrations.CreateModel(
            name='Clases',
            fields=[
                ('cla_id', models.AutoField(primary_key=True, serialize=False)),
                ('cla_nombre', models.CharField(max_length=100, verbose_name='Clase:')),
                ('cla_estado', models.BooleanField(default=True, verbose_name='Estado:')),
                ('cla_fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Creado el:')),
                ('cla_fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Actualizado el:')),
                ('fk_docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.docentes', verbose_name='Docente')),
                ('fk_modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.modulos', verbose_name='Modulo')),
            ],
        ),
        migrations.CreateModel(
            name='Matriculas',
            fields=[
                ('mat_id', models.AutoField(primary_key=True, serialize=False)),
                ('mat_estado', models.BooleanField(default=True, verbose_name='Estado:')),
                ('mat_fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Creado el:')),
                ('mat_fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Actualizado el:')),
                ('fk_clase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.clases', verbose_name='Clase')),
                ('fk_estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.estudiantes', verbose_name='Estudiante')),
            ],
        ),
        migrations.CreateModel(
            name='Niveles',
            fields=[
                ('niv_id', models.AutoField(primary_key=True, serialize=False)),
                ('niv_nombre', models.CharField(max_length=50, verbose_name='Nombre del nivel:')),
                ('niv_descripcion', models.CharField(max_length=100, verbose_name='Descripción del nivel:')),
                ('orden', models.IntegerField()),
                ('vidas', models.IntegerField()),
                ('ruta', models.CharField(max_length=100, null=True, verbose_name='Ruta:')),
                ('niv_estado', models.BooleanField(default=True, verbose_name='Estado:')),
                ('niv_fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Creado el:')),
                ('niv_fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Actualizado el:')),
                ('fk_modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.modulos', verbose_name='Modulo')),
            ],
        ),
        migrations.CreateModel(
            name='IntentoNivel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_nota', models.DecimalField(blank=True, decimal_places=2, help_text='Nota obtenida en el intento', max_digits=5, null=True)),
                ('in_fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Creado el:')),
                ('in_fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Actualizado el:')),
                ('in_vidas_usadas', models.IntegerField(blank=True, help_text='Número de vidas utilizadas en el intento', null=True)),
                ('fk_matricula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.matriculas', verbose_name='Matricula')),
                ('fk_nivel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.niveles', verbose_name='Niveles')),
            ],
            options={
                'verbose_name': 'Intento de Nivel',
                'verbose_name_plural': 'Intentos de Nivel',
                'db_table': 'intento_nivel',
                'ordering': ['-in_fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Enunciados',
            fields=[
                ('enun_id', models.AutoField(primary_key=True, serialize=False)),
                ('enun_nombre', models.CharField(max_length=100, verbose_name='Enunciado:')),
                ('enum_puntaje', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Puntaje:')),
                ('enun_estado', models.BooleanField(default=True, verbose_name='Estado:')),
                ('enun_fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Creado el:')),
                ('enun_fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Actualizado el:')),
                ('fk_nivel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.niveles', verbose_name='Nivel')),
            ],
        ),
        migrations.CreateModel(
            name='Avance_Matriculados',
            fields=[
                ('avm_id', models.AutoField(primary_key=True, serialize=False)),
                ('avm_nota_final', models.DecimalField(blank=True, decimal_places=2, help_text='Mejor nota obtenida en el nivel', max_digits=5, null=True)),
                ('avm_estado', models.CharField(blank=True, choices=[('iniciado', 'Iniciado'), ('en_progreso', 'En Progreso'), ('completado', 'Completado'), ('aprobado', 'Aprobado'), ('reprobado', 'Reprobado'), ('sin_vidas', 'Sin Vidas')], default='iniciado', max_length=20, null=True)),
                ('avm_fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Creado el:')),
                ('avm_fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Actualizado el:')),
                ('avm_vidas_restantes', models.IntegerField(blank=True, help_text='Vidas restantes para este nivel', null=True)),
                ('avm_ultimo_intento', models.DateTimeField(blank=True, help_text='Fecha del último intento realizado', null=True)),
                ('avm_vidas_iniciales_nivel', models.IntegerField(blank=True, help_text='Vidas iniciales que tenía el nivel cuando el estudiante se matriculó', null=True)),
                ('fk_matricula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.matriculas', verbose_name='Matricula')),
                ('fk_nivel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.niveles', verbose_name='Niveles')),
            ],
            options={
                'verbose_name': 'Avance de Estudiante',
                'verbose_name_plural': 'Avances de Estudiantes',
                'db_table': 'avance_estudiante',
                'ordering': ['fk_matricula', 'fk_nivel'],
            },
        ),
        migrations.CreateModel(
            name='Personas',
            fields=[
                ('per_id', models.AutoField(primary_key=True, serialize=False)),
                ('per_segundo_nombre', models.CharField(default='Null', max_length=50, verbose_name='Segundo nombre:')),
                ('per_segundo_apellido', models.CharField(default='Null', max_length=50, verbose_name='Segundo apellido:')),
                ('per_fecha_nacimiento', models.DateField(blank=True, default=None, null=True, verbose_name='Fecha de nacimiento:')),
                ('per_cedula', models.CharField(default='Null', max_length=15, verbose_name='Cédula:')),
                ('per_telefono', models.CharField(default='Null', max_length=15, null=True, verbose_name='Teléfono:')),
                ('per_fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Actualizado el:')),
                ('fk_id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
        ),
        migrations.AddField(
            model_name='estudiantes',
            name='fk_id_persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.personas', verbose_name='Persona'),
        ),
        migrations.AddField(
            model_name='docentes',
            name='fk_id_persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.personas', verbose_name='Persona'),
        ),
        migrations.CreateModel(
            name='Administradores',
            fields=[
                ('adm_id', models.AutoField(primary_key=True, serialize=False)),
                ('adm_fotografia', models.ImageField(blank=True, default='Sin Foto', null=True, upload_to='', verbose_name='Fotografía:')),
                ('adm_estado', models.BooleanField(default=True, verbose_name='Estado:')),
                ('fk_id_persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.personas', verbose_name='Persona')),
            ],
        ),
        migrations.CreateModel(
            name='Preguntas',
            fields=[
                ('pre_id', models.AutoField(primary_key=True, serialize=False)),
                ('pre_nombre', models.CharField(max_length=100, verbose_name='Pregunta:')),
                ('pre_tiene_imagen', models.BooleanField(default=False, verbose_name='Tiene imagen:')),
                ('pre_imagen', models.ImageField(blank=True, default='Sin Foto', null=True, upload_to='preguntas/', verbose_name='Imagen:')),
                ('pre_estado', models.BooleanField(default=True, verbose_name='Estado:')),
                ('pre_fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Creado el:')),
                ('pre_fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Actualizado el:')),
                ('fk_enunciado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.enunciados', verbose_name='Enunciado')),
            ],
        ),
        migrations.CreateModel(
            name='Opciones',
            fields=[
                ('op_id', models.AutoField(primary_key=True, serialize=False)),
                ('op_nombre', models.CharField(max_length=100, verbose_name='Opcion:')),
                ('op_correcta', models.BooleanField(default=False, verbose_name='Correcta:')),
                ('op_estado', models.BooleanField(default=True, verbose_name='Estado:')),
                ('op_fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Creado el:')),
                ('op_fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Actualizado el:')),
                ('fk_pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.preguntas', verbose_name='Pregunta')),
            ],
        ),
        migrations.AddConstraint(
            model_name='niveles',
            constraint=models.UniqueConstraint(fields=('fk_modulo', 'niv_nombre'), name='unique_nombre_por_modulo'),
        ),
        migrations.AlterUniqueTogether(
            name='avance_matriculados',
            unique_together={('fk_matricula', 'fk_nivel')},
        ),
    ]
