# Generated by Django 5.1 on 2025-06-23 14:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avance_matriculados',
            name='avm_vidas_iniciales_nivel',
        ),
        migrations.CreateModel(
            name='Vidas_Extras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vidas_asignadas', models.IntegerField(help_text='Vidas totales asignadas para este estudiante en este nivel (puede ser menor, igual o mayor a las vidas iniciales del nivel)')),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('observaciones', models.TextField(blank=True, help_text='Razón del cambio de vidas', null=True)),
                ('asignado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('matricula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.matriculas')),
                ('nivel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.niveles')),
            ],
            options={
                'verbose_name': 'Vida Extra',
                'verbose_name_plural': 'Vidas Extras',
                'unique_together': {('matricula', 'nivel')},
            },
        ),
    ]
