# Generated by Django 5.2.3 on 2025-06-23 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='niveles',
            name='ruta',
            field=models.CharField(max_length=100, null=True, verbose_name='Ruta:'),
        ),
        migrations.AlterField(
            model_name='niveles',
            name='niv_nombre',
            field=models.CharField(max_length=50, verbose_name='Nombre del nivel:'),
        ),
        migrations.AddConstraint(
            model_name='niveles',
            constraint=models.UniqueConstraint(fields=('fk_modulo', 'niv_nombre'), name='unique_nombre_por_modulo'),
        ),
    ]
