# Generated by Django 5.1 on 2025-06-23 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_avance_matriculados_avm_vidas_iniciales_nivel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vidas_extras',
            name='vidas_aplicadas',
            field=models.BooleanField(default=False),
        ),
    ]
