# Generated by Django 5.2.3 on 2025-06-24 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_niveles_ruta_alter_niveles_niv_nombre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personas',
            name='per_fecha_nacimiento',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento:'),
        ),
    ]
