# Generated by Django 5.0.6 on 2025-06-16 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_administradores_adm_fecha_actualizacion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administradores',
            name='adm_fecha_creacion',
        ),
    ]
