# Generated by Django 5.0.6 on 2025-06-16 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_administradores_adm_fecha_creacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='administradores',
            name='adm_fotografia',
            field=models.ImageField(blank=True, default='Sin Foto', null=True, upload_to='administradores/', verbose_name='Fotografía:'),
        ),
    ]
