# Generated by Django 5.2.3 on 2025-06-25 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_personas_per_fecha_nacimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='niveles',
            name='fk_modulo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='niveles', to='core.modulos', verbose_name='Modulo'),
        ),
    ]
