# Generated by Django 5.2.3 on 2025-06-26 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_niveles_fk_modulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administradores',
            name='adm_fotografia',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='administradores/', verbose_name='Fotografía:'),
        ),
        migrations.AlterField(
            model_name='docentes',
            name='doc_fotografia',
            field=models.ImageField(default=None, upload_to='docentes/', verbose_name='Fotografía:'),
        ),
        migrations.AlterField(
            model_name='estudiantes',
            name='est_fotografia',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='estudiantes/', verbose_name='Fotografía:'),
        ),
    ]
