# Generated by Django 5.2.3 on 2025-06-16 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_personas_per_edad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modulos',
            fields=[
                ('mod_id', models.AutoField(primary_key=True, serialize=False)),
                ('mod_nombre', models.CharField(max_length=50, verbose_name='Nombre del modulo:')),
                ('mod_descripcion', models.CharField(max_length=100, verbose_name='Descripción del modulo:')),
                ('mod_estado', models.BooleanField(default=True, verbose_name='Estado:')),
                ('mod_fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Creado el:')),
                ('mod_fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Actualizado el:')),
            ],
        ),
        migrations.AlterField(
            model_name='administradores',
            name='adm_fotografia',
            field=models.ImageField(blank=True, default='Sin Foto', null=True, upload_to='', verbose_name='Fotografía:'),
        ),
    ]
