# Generated by Django 5.2.3 on 2025-06-16 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_modulos_alter_administradores_adm_fotografia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modulos',
            name='mod_nombre',
            field=models.CharField(max_length=50, unique=True, verbose_name='Nombre del modulo:'),
        ),
    ]
