# Generated by Django 5.2.3 on 2025-06-17 02:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_modulos_mod_nombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Niveles',
            fields=[
                ('niv_id', models.AutoField(primary_key=True, serialize=False)),
                ('niv_nombre', models.CharField(max_length=50, unique=True, verbose_name='Nombre del nivel:')),
                ('niv_descripcion', models.CharField(max_length=100, verbose_name='Descripción del nivel:')),
                ('orden', models.IntegerField()),
                ('vidas', models.IntegerField()),
                ('niv_estado', models.BooleanField(default=True, verbose_name='Estado:')),
                ('niv_fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Creado el:')),
                ('niv_fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Actualizado el:')),
                ('fk_modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.modulos', verbose_name='Modulo')),
            ],
        ),
    ]
