# Generated by Django 5.2.3 on 2025-06-19 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_niveles_enunciados_preguntas_opciones_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='niveles',
            name='ruta',
            field=models.CharField(max_length=100, null=True, verbose_name='Ruta:'),
        ),
        migrations.CreateModel(
            name='Clases',
            fields=[
                ('cla_id', models.AutoField(primary_key=True, serialize=False)),
                ('cla_nombre', models.CharField(max_length=100, verbose_name='Clase:')),
                ('cla_estado', models.BooleanField(default=True, verbose_name='Estado:')),
                ('cla_fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Creado el:')),
                ('cla_fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Actualizado el:')),
                ('fk_docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.docentes', verbose_name='Docente')),
                ('fk_modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.modulos', verbose_name='Modulo')),
            ],
        ),
    ]
