# Generated by Django 5.2.3 on 2025-06-17 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_niveles'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enunciados',
            fields=[
                ('enun_id', models.AutoField(primary_key=True, serialize=False)),
                ('enun_nombre', models.CharField(max_length=100, verbose_name='Enunciado:')),
                ('enun_estado', models.BooleanField(default=True, verbose_name='Estado:')),
                ('enun_fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Creado el:')),
                ('enun_fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Actualizado el:')),
                ('fk_nivel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.niveles', verbose_name='Nivel')),
            ],
        ),
        migrations.CreateModel(
            name='Preguntas',
            fields=[
                ('pre_id', models.AutoField(primary_key=True, serialize=False)),
                ('pre_nombre', models.CharField(max_length=100, verbose_name='Pregunta:')),
                ('pre_tiene_imagen', models.BooleanField(default=False, verbose_name='Tiene imagen:')),
                ('pre_imagen', models.ImageField(blank=True, default='Sin Foto', null=True, upload_to='preguntas/', verbose_name='Imagen:')),
                ('pre_estado', models.BooleanField(default=True, verbose_name='Estado:')),
                ('pre_fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Creado el:')),
                ('pre_fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Actualizado el:')),
                ('fk_enunciado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.enunciados', verbose_name='Enunciado')),
            ],
        ),
        migrations.CreateModel(
            name='Opciones',
            fields=[
                ('op_id', models.AutoField(primary_key=True, serialize=False)),
                ('op_nombre', models.CharField(max_length=100, verbose_name='Opcion:')),
                ('op_correcta', models.BooleanField(default=False, verbose_name='Correcta:')),
                ('op_estado', models.BooleanField(default=True, verbose_name='Estado:')),
                ('op_fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Creado el:')),
                ('op_fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Actualizado el:')),
                ('fk_pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.preguntas', verbose_name='Pregunta')),
            ],
        ),
    ]
