# Generated by Django 5.2.3 on 2025-06-19 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_niveles_ruta_clases'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matriculas',
            fields=[
                ('mat_id', models.AutoField(primary_key=True, serialize=False)),
                ('mat_estado', models.BooleanField(default=True, verbose_name='Estado:')),
                ('mat_fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Creado el:')),
                ('mat_fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Actualizado el:')),
                ('fk_clase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.clases', verbose_name='Clase')),
                ('fk_estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.estudiantes', verbose_name='Estudiante')),
            ],
        ),
    ]
