# Generated by Django 5.1 on 2025-06-19 19:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_enunciados_preguntas_opciones'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IntentoNivel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.DecimalField(blank=True, decimal_places=2, help_text='Nota obtenida en el intento', max_digits=5, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True, null=True)),
                ('vidas_usadas', models.IntegerField(blank=True, default=0, help_text='Número de vidas utilizadas en el intento', null=True)),
                ('estudiante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='intentos_nivel', to=settings.AUTH_USER_MODEL)),
                ('nivel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='intentos', to='core.niveles')),
            ],
            options={
                'verbose_name': 'Intento de Nivel',
                'verbose_name_plural': 'Intentos de Nivel',
                'db_table': 'intento_nivel',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='AvanceEstudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(blank=True, choices=[('iniciado', 'Iniciado'), ('en_progreso', 'En Progreso'), ('completado', 'Completado'), ('aprobado', 'Aprobado'), ('reprobado', 'Reprobado')], default='iniciado', max_length=20, null=True)),
                ('nota_final', models.DecimalField(blank=True, decimal_places=2, help_text='Mejor nota obtenida en el nivel', max_digits=5, null=True)),
                ('estudiante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='avances', to=settings.AUTH_USER_MODEL)),
                ('nivel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='avances_estudiantes', to='core.niveles')),
            ],
            options={
                'verbose_name': 'Avance de Estudiante',
                'verbose_name_plural': 'Avances de Estudiantes',
                'db_table': 'avance_estudiante',
                'ordering': ['estudiante', 'nivel'],
                'unique_together': {('estudiante', 'nivel')},
            },
        ),
    ]
