# Generated by Django 5.2.3 on 2025-06-20 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_matriculas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personas',
            name='per_fecha_nacimiento',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Fecha de nacimiento:'),
        ),
    ]
