# Generated by Django 5.1 on 2025-06-20 00:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_intentonivel_avanceestudiante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intentonivel',
            name='estudiante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='intentos_nivel', to='core.estudiantes'),
        ),
    ]
