# Generated by Django 5.1 on 2025-06-20 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_intentonivel_estudiante'),
    ]

    operations = [
        migrations.AddField(
            model_name='avanceestudiante',
            name='ultimo_intento',
            field=models.DateTimeField(blank=True, help_text='Fecha del último intento realizado', null=True),
        ),
        migrations.AddField(
            model_name='avanceestudiante',
            name='vidas_restantes',
            field=models.IntegerField(blank=True, default=0, help_text='Vidas restantes para este nivel', null=True),
        ),
        migrations.AlterField(
            model_name='avanceestudiante',
            name='estado',
            field=models.CharField(blank=True, choices=[('iniciado', 'Iniciado'), ('en_progreso', 'En Progreso'), ('completado', 'Completado'), ('aprobado', 'Aprobado'), ('reprobado', 'Reprobado'), ('sin_vidas', 'Sin Vidas')], default='iniciado', max_length=20, null=True),
        ),
    ]
