# Generated by Django 5.2.3 on 2025-06-20 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_personas_per_fecha_nacimiento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avance_Matriculados',
            fields=[
                ('avm_id', models.AutoField(primary_key=True, serialize=False)),
                ('avm_nota_final', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Nota:')),
                ('avm_estado', models.BooleanField(default=True, verbose_name='Estado:')),
                ('avm_fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Creado el:')),
                ('avm_fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Actualizado el:')),
                ('fk_matricula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.matriculas', verbose_name='Matricula')),
                ('fk_nivel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.niveles', verbose_name='Nivel')),
            ],
        ),
    ]
