# Generated by Django 5.1 on 2025-06-23 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_avanceestudiante_ultimo_intento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='avanceestudiante',
            name='vidas_iniciales_nivel',
            field=models.IntegerField(blank=True, default=0, help_text='Vidas que tenía el nivel cuando el estudiante empezó', null=True),
        ),
    ]
