"""
Django settings for matematicas project.

Generated by 'django-admin startproject' using Django 5.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
import dj_database_url
# para los mensajes
from django.contrib.messages import constants as messages

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY', 'django-insecure-kg5lwvu9%k18^wnf3a=fiybm3n00ld1mttd_4azo+9&0y+_#0y')

# SECURITY WARNING: don't run with debug turned on in production!
# Configuración mejorada: DEBUG=True por defecto en desarrollo
DEBUG = os.getenv('DEBUG', 'True').lower() in ['true', '1', 'yes']


# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'widget_tweaks', # para mejorar la interfaz de usuario
    'Aplicaciones.core'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # Para servir archivos estáticos en Railway
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',  # MOVIDO ANTES del middleware personalizado
    'Aplicaciones.core.middleware.LoginAndNoCacheMiddleware', # Middleware personalizado para evitar caché
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'matematicas.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],  # ← Ya tienes esto corregido
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'Aplicaciones.core.context_processors.foto_perfil_usuario', # Context processor personalizado para la foto de perfil del usuario
            ],
        },
    },
]

WSGI_APPLICATION = 'matematicas.wsgi.application'

# Database - Automático: PostgreSQL en Railway, SQLite en desarrollo
if 'DATABASE_URL' in os.environ:
    DATABASES = {
        'default': dj_database_url.config(
            default=os.getenv('DATABASE_URL'),
            conn_max_age=600,
            ssl_require=True
        )
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/
LANGUAGE_CODE = 'es-ec'
TIME_ZONE = 'America/Guayaquil'
USE_I18N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/
STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'matematicas/static']
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Configuración de WhiteNoise para archivos estáticos en Railway
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Media (para imágenes)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# para los mensajes
MESSAGE_STORAGE = 'django.contrib.messages.storage.session.SessionStorage'

MESSAGE_TAGS = {
    messages.DEBUG: 'debug',
    messages.INFO: 'info',
    messages.SUCCESS: 'success',
    messages.WARNING: 'warning',
    messages.ERROR: 'error',
}

# ===== CONFIGURACIÓN DE SESIONES =====
SESSION_COOKIE_AGE = 3600  # 1 hora
SESSION_EXPIRE_AT_BROWSER_CLOSE = True
SESSION_SAVE_EVERY_REQUEST = True
SESSION_COOKIE_HTTPONLY = True

# ===== CONFIGURACIÓN DE LOGIN =====
LOGIN_URL = '/loguin/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/loguin/'

# ===== CONFIGURACIÓN ESPECÍFICA POR ENTORNO =====
if DEBUG:
    # ===== CONFIGURACIÓN DE DESARROLLO =====
    print("🟢 Ejecutando en modo DESARROLLO")
    ALLOWED_HOSTS = ['127.0.0.1', 'localhost', '0.0.0.0', '::1']
    
    # Seguridad relajada para desarrollo local
    SESSION_COOKIE_SECURE = False
    CSRF_COOKIE_SECURE = False
    SECURE_SSL_REDIRECT = False
    # Configuraciones específicas para Brave y otros navegadores estrictos
    SECURE_BROWSER_XSS_FILTER = False  # Desactivar en desarrollo
    SECURE_CONTENT_TYPE_NOSNIFF = False  # Desactivar en desarrollo
    
    # Headers adicionales para compatibilidad
    SECURE_CROSS_ORIGIN_OPENER_POLICY = None
    SECURE_REFERRER_POLICY = None
    
    # Configuración de CORS para desarrollo (si usas CORS)
    CORS_ALLOW_ALL_ORIGINS = True  # Solo en desarrollo
    CORS_ALLOW_CREDENTIALS = True
    
    # Logging detallado para desarrollo
    LOGGING = {
        'version': 1,
        'disable_existing_loggers': False,
        'formatters': {
            'verbose': {
                'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
                'style': '{',
            },
            'simple': {
                'format': '{levelname} {message}',
                'style': '{',
            },
        },
        'handlers': {
            'console': {
                'class': 'logging.StreamHandler',
                'formatter': 'simple',
            },
            'file': {
                'class': 'logging.FileHandler',
                'filename': BASE_DIR / 'login_debug.log',
                'formatter': 'verbose',
            },
        },
        'loggers': {
            'Aplicaciones.core.views': {  # Para tus views de login
                'handlers': ['console', 'file'],
                'level': 'DEBUG',
                'propagate': False,
            },
            'Aplicaciones.core.middleware': {  # Para debugging del middleware
                'handlers': ['console', 'file'],
                'level': 'DEBUG',
                'propagate': False,
            },
            'django.contrib.auth': {  # Para debug de autenticación
                'handlers': ['console'],
                'level': 'DEBUG',
                'propagate': False,
            },
        },
        'root': {
            'handlers': ['console'],
            'level': 'INFO',
        },
    }
    
else:
    # ===== CONFIGURACIÓN DE PRODUCCIÓN =====
    print("🔴 Ejecutando en modo PRODUCCIÓN")
    
    ALLOWED_HOSTS = ['159.69.216.217', 'localhost', '127.0.0.1']
    
    # Base de datos PostgreSQL para VPS (si no hay DATABASE_URL)
    if 'DATABASE_URL' not in os.environ:
        DATABASES = {
            'default': {
                'ENGINE': 'django.db.backends.postgresql',
                'NAME': 'matematicas_db',
                'USER': 'matematicas_user',
                'PASSWORD': 'matematicas_dj_123',
                'HOST': 'localhost',
                'PORT': '5432',
            }
        }
    
    
    # Seguridad estricta para producción
    # SESSION_COOKIE_SECURE = True
    # CSRF_COOKIE_SECURE = True
    # SECURE_BROWSER_XSS_FILTER = True
    # SECURE_CONTENT_TYPE_NOSNIFF = True
    # SECURE_REFERRER_POLICY = 'same-origin'
    # SECURE_SSL_REDIRECT = True
    # SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    
    # Logging simplificado para producción
    LOGGING = {
        'version': 1,
        'disable_existing_loggers': False,
        'formatters': {
            'verbose': {
                'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
                'style': '{',
            },
        },
        'handlers': {
            'console': {
                'class': 'logging.StreamHandler',
                'formatter': 'verbose',
            },
        },
        'root': {
            'handlers': ['console'],
            'level': 'INFO',
        },
        'loggers': {
            'django': {
                'handlers': ['console'],
                'level': 'INFO',
                'propagate': False,
            },
            'Aplicaciones.core.views': {
                'handlers': ['console'],
                'level': 'INFO',
                'propagate': False,
            },
        },
    }


